/// Flutter icons SuizerliLogo
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SuizerliLogo
///      fonts:
///       - asset: fonts/SuizerliLogo.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SuizerliLogo {
  SuizerliLogo._();

  static const _kFontFam = 'SuizerliLogo';

  static const IconData suizerli_logo_up = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData suizerli_logo_down = const IconData(0xe801, fontFamily: _kFontFam);
}
